---
name: CI Demo

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # we need git client so we can git clone repo
      - name: Sleep for a while
        run: |
          sleep 60
