---
name: CI Demo
on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # we need git client so we can git clone repo
      - name: Sleep for a while
        run: |
          sleep 3
